<x-layouts.app title="{{ $nexusAppearance['site_name'] }}">
@php($totalPlayers=$servers->sum('players_online')) @php($totalSlots=max(1,$servers->sum('players_max'))) @php($onlineServers=$servers->where('status','online')->count())
<div class="n3-content"><div class="n3-wrap">
    <section><div class="n3-heading"><div><span class="n3-eyebrow">{{ app()->getLocale()==='bg'?'Мрежа в реално време':'Live network' }}</span><h1>{{ app()->getLocale()==='bg'?'Избери своя режим':'Choose your mode' }}</h1></div><div class="n3-tabs"><button class="n3-tab active">{{ app()->getLocale()==='bg'?'Сървъри':'Servers' }}</button><button class="n3-tab">{{ app()->getLocale()==='bg'?'Последни наказания':'Latest bans' }}</button><button class="n3-tab">{{ app()->getLocale()==='bg'?'Нови играчи':'New players' }}</button></div></div>
        <div class="n3-modes">@forelse($servers as $server)<article class="n3-mode" style="background-image:url('{{ $server->mapArtwork() }}')"><div class="n3-mode-top"><span class="n3-game">{{ strtoupper($server->game) }}</span><span class="n3-state {{ $server->status==='online'?'online':'offline' }}">{{ $server->status }}</span></div><div class="n3-mode-body"><h3>{{ $server->name }}</h3><div class="n3-mode-meta"><span>{{ $server->current_map?:'Awaiting query' }}</span><span>{{ $server->latency_ms?$server->latency_ms.' ms':'—' }}</span><span class="n3-count">{{ $server->players_online }}<small>/{{ $server->players_max }}</small></span></div></div><a class="absolute inset-0" href="steam://connect/{{ $server->host }}:{{ $server->port }}"></a></article>@empty @foreach(['PUBLIC','AWP ONLY','RETAKE','DEATHMATCH'] as $mode)<article class="n3-mode" style="background-image:url('{{ asset('images/maps/'.(['dust','mirage','inferno','nuke'][$loop->index]).'.svg') }}')"><div class="n3-mode-top"><span class="n3-game">CS2</span><span class="n3-state offline">offline</span></div><div class="n3-mode-body"><h3>{{ $mode }}</h3><div class="n3-mode-meta"><span>Awaiting setup</span><span class="n3-count">0<small>/0</small></span></div></div></article>@endforeach @endforelse</div>
    </section>
    <section class="n3-section n3-promos"><a class="n3-promo" href="{{ route('community.index') }}" style="--glow:#1f9fd066"><b>{{ app()->getLocale()==='bg'?'Присъедини се към Telegram':'Join our Telegram' }}</b><small>{{ app()->getLocale()==='bg'?'Новини и връзка с екипа':'News and direct support' }}</small><i class="n3-promo-mark">T</i></a><a class="n3-promo" href="{{ route('community.index') }}" style="--glow:#e42d3f55"><b>{{ app()->getLocale()==='bg'?'Нашият YouTube канал':'Our YouTube channel' }}</b><small>{{ app()->getLocale()==='bg'?'Клипове, стриймове и събития':'Videos, streams and events' }}</small><i class="n3-promo-mark">▶</i></a><a class="n3-promo" href="{{ route('shop.index') }}" style="--glow:#8059dd55"><b>{{ app()->getLocale()==='bg'?'Премиум услуги':'Premium services' }}</b><small>{{ app()->getLocale()==='bg'?'VIP и специални възможности':'VIP and special features' }}</small><i class="n3-promo-mark">VIP</i></a></section>
    <section class="n3-section n3-home-grid"><div class="n3-panel"><header class="n3-panel-head"><div><span class="n3-eyebrow">Community feed</span><h2>{{ app()->getLocale()==='bg'?'Последни новини':'Latest news' }}</h2></div><a href="{{ route('news.index') }}">{{ app()->getLocale()==='bg'?'Всички новини':'View all' }} →</a></header>@forelse($posts as $post)<a class="n3-news" href="{{ route('news.show',$post) }}"><span class="n3-news-image" @if($post->imageUrl()) style="background-image:url('{{ $post->imageUrl() }}')" @endif></span><span><small class="n3-eyebrow">{{ $post->category }} · {{ $post->published_at->format('d.m.Y') }}</small><h3>{{ $post->title }}</h3><p>{{ $post->excerpt }}</p></span><i class="n3-arrow">→</i></a>@empty<div class="p-14 text-center text-xs text-slate-500">{{ app()->getLocale()==='bg'?'Все още няма публикувани новини.':'No news published yet.' }}</div>@endforelse</div>
        <aside class="n3-stat-stack"><section class="n3-panel n3-stat"><h3>{{ app()->getLocale()==='bg'?'Статус на мрежата':'Network status' }}</h3><div class="n3-stat-row"><span>{{ app()->getLocale()==='bg'?'Активни сървъри':'Active servers' }}</span><b>{{ $onlineServers }}/{{ $servers->count() }}</b></div><div class="n3-stat-row"><span>{{ app()->getLocale()==='bg'?'Заетост':'Occupancy' }}</span><b>{{ round(($totalPlayers/$totalSlots)*100) }}%</b></div><div class="n3-stat-row"><span>{{ app()->getLocale()==='bg'?'Играчи онлайн':'Players online' }}</span><b>{{ $totalPlayers }}</b></div></section><section class="n3-panel n3-stat"><h3>{{ app()->getLocale()==='bg'?'Твоят профил':'Your profile' }}</h3><div class="n3-stat-row"><span>Steam</span><b>{{ auth()->check()?'✓':'—' }}</b></div><div class="n3-stat-row"><span>{{ app()->getLocale()==='bg'?'Акаунт':'Account' }}</span><a href="{{ auth()->check()?route('profile.show',auth()->user()):route('login') }}">{{ auth()->check()?auth()->user()->name:(app()->getLocale()==='bg'?'Вход':'Sign in') }} →</a></div></section></aside>
    </section>
</div></div>
</x-layouts.app>
