<!doctype html>
<html lang="{{ str_replace('_','-',app()->getLocale()) }}">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="csrf-token" content="{{ csrf_token() }}"><title>{{ $title ?? $nexusAppearance['site_name'] }}</title><meta name="description" content="{{ $nexusAppearance['site_tagline'] }}"><meta name="theme-color" content="#151922">@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="portal-public" style="--accent:{{ $nexusAppearance['accent'] }};--accent2:{{ $nexusAppearance['accent'] }}">
<div class="portal-top"><div class="portal-shell"><span>WELCOME TO {{ strtoupper($nexusAppearance['site_name']) }}</span><nav><a href="{{ route('news.index') }}">NEWS</a><a href="{{ route('about') }}">ABOUT</a><a href="{{ route('locale.switch',app()->getLocale()==='bg'?'en':'bg') }}">{{ app()->getLocale()==='bg'?'EN':'BG' }}</a></nav></div></div>
<header class="portal-masthead"><div class="portal-shell"><a class="portal-logo" href="{{ route('home') }}"><span>N</span><div><b>{{ strtoupper($nexusAppearance['site_name']) }}</b><small>{{ $nexusAppearance['site_tagline'] }}</small></div></a><div class="portal-head-copy"><small>EST. 2026 · GAMING COMMUNITY</small><b>PLAY. COMPETE. BELONG.</b></div><div class="portal-account">@auth<div><small>WELCOME BACK</small><b>{{ auth()->user()->name }}</b></div><a href="{{ route('profile.show',auth()->user()) }}">PROFILE</a>@if(auth()->user()->isAdmin())<a href="{{ route('admin.dashboard') }}">ADMIN</a>@endif @else<div><small>MEMBER AREA</small><b>JOIN THE NETWORK</b></div><a href="{{ route('login') }}">SIGN IN</a>@endauth</div></div></header>
<div class="portal-nav-wrap"><div class="portal-shell">
    <nav class="portal-nav">
        <a class="{{ request()->routeIs('home')?'active':'' }}" href="{{ route('home') }}"><b>01</b>{{ __('ui.nav.home') }}</a>
        <a class="{{ request()->routeIs('servers.*')?'active':'' }}" href="{{ route('servers.index') }}"><b>02</b>{{ __('ui.nav.servers') }}</a>
        <a class="{{ request()->routeIs('news.*')?'active':'' }}" href="{{ route('news.index') }}"><b>03</b>NEWS</a>
        <a class="{{ request()->routeIs('community.*')?'active':'' }}" href="{{ route('community.index') }}"><b>04</b>{{ __('ui.nav.community') }}</a>
        <a class="{{ request()->routeIs('shop.*')?'active':'' }}" href="{{ route('shop.index') }}"><b>05</b>{{ __('ui.nav.shop') }}</a>
        <a class="{{ request()->routeIs('bans.*')?'active':'' }}" href="{{ route('bans.index') }}"><b>06</b>{{ __('ui.nav.bans') }}</a>
        <a class="{{ request()->routeIs('about')?'active':'' }}" href="{{ route('about') }}"><b>07</b>ABOUT</a>
    </nav>
    <details class="mobile-menu"><summary aria-label="Open navigation"><span><small>NEXUS NETWORK</small><b>MENU</b></span><i></i></summary><div class="mobile-drawer"><header><div class="portal-logo small"><span>N</span><div><b>NEXUS</b><small>MAIN NAVIGATION</small></div></div><button type="button" data-close-menu>×</button></header><nav><a class="{{ request()->routeIs('home')?'active':'' }}" href="{{ route('home') }}"><b>01</b><span>Начало<small>Network overview</small></span></a><a class="{{ request()->routeIs('servers.*')?'active':'' }}" href="{{ route('servers.index') }}"><b>02</b><span>Сървъри<small>Live game network</small></span></a><a class="{{ request()->routeIs('news.*')?'active':'' }}" href="{{ route('news.index') }}"><b>03</b><span>Новини<small>Updates & articles</small></span></a><a class="{{ request()->routeIs('community.*')?'active':'' }}" href="{{ route('community.index') }}"><b>04</b><span>Общност<small>Members & profiles</small></span></a><a class="{{ request()->routeIs('shop.*')?'active':'' }}" href="{{ route('shop.index') }}"><b>05</b><span>Магазин<small>VIP & services</small></span></a><a class="{{ request()->routeIs('bans.*')?'active':'' }}" href="{{ route('bans.index') }}"><b>06</b><span>Ban List<small>Security registry</small></span></a><a class="{{ request()->routeIs('about')?'active':'' }}" href="{{ route('about') }}"><b>07</b><span>За нас<small>About the network</small></span></a></nav><footer><a href="{{ route('locale.switch',app()->getLocale()==='bg'?'en':'bg') }}">LANG: {{ strtoupper(app()->getLocale()) }}</a>@auth<a href="{{ route('profile.show',auth()->user()) }}">MY PROFILE</a>@if(auth()->user()->isAdmin())<a href="{{ route('admin.dashboard') }}">CONTROL CENTER</a>@endif<form method="POST" action="{{ route('logout') }}">@csrf<button>LOG OUT</button></form>@else<a href="{{ route('login') }}">SIGN IN</a>@endauth</footer></div></details>
</div></div>
<div class="portal-ticker"><div class="portal-shell"><b>NETWORK NEWS</b><span>•</span><p>NEXUS community platform is online — live servers, news and Steam identity connected.</p><time>{{ now()->format('d.m.Y') }}</time></div></div>
<main>{{ $slot }}</main>
<footer class="portal-footer"><div class="portal-shell"><div class="portal-logo small"><span>N</span><div><b>{{ strtoupper($nexusAppearance['site_name']) }}</b><small>GAME COMMUNITY</small></div></div><nav><a href="{{ route('news.index') }}">NEWS</a><a href="{{ route('servers.index') }}">SERVERS</a><a href="{{ route('community.index') }}">COMMUNITY</a><a href="{{ route('about') }}">ABOUT</a></nav><p>Powered by NEXUS Engine<br>© {{ date('Y') }} All rights reserved.</p></div></footer>
</body></html>
