@extends('layouts.app')
@section('title', 'Skinchanger — NEXUS')
@section('content')
@include('partials.page-header', ['eyebrow'=>'PERSONAL LOADOUT','title'=>'Skinchanger','description'=>'Създавай и управлявай персонални колекции за поддържаните сървъри.'])
<section class="loadout-layout">
<aside class="panel loadout-sidebar"><div class="loadout-profile"><span class="avatar avatar-lg avatar-gradient">RS</span><div><strong>ROG_STRIX</strong><small>Колекция: Neon Core</small></div></div><button class="button button-primary width-full">@svg('sparkles') Нова колекция</button><div class="collection-list"><button class="is-active"><span class="collection-preview g-purple"></span><span><strong>Neon Core</strong><small>6 оръжия</small></span></button><button><span class="collection-preview g-orange"></span><span><strong>Golden Dust</strong><small>4 оръжия</small></span></button><button><span class="collection-preview g-cyan"></span><span><strong>Printstream</strong><small>3 оръжия</small></span></button></div><div class="loadout-tip"><span>@svg('help')</span><p>Колекциите се синхронизират автоматично при влизане в сървър.</p></div></aside>
<div class="loadout-main"><div class="loadout-toolbar"><div class="input-shell">@svg('search')<input placeholder="Търси оръжие или skin..."></div><div class="segmented"><button class="is-active">Всички</button><button>Rifles</button><button>Pistols</button></div></div><div class="weapon-grid">@foreach($weapons as $weapon)<article class="weapon-card"><div class="weapon-art {{ $weapon['gradient'] }}"><span>{{ $weapon['name'] }}</span><i></i></div><div><small>{{ $weapon['name'] }}</small><h3>{{ $weapon['skin'] }}</h3><div><span>{{ $weapon['kills'] }} kills</span><button>@svg('settings')</button></div></div></article>@endforeach</div><div class="loadout-save"><span><i></i> Има незапазени промени</span><div><button class="button button-muted">Отказ</button><button class="button button-primary">@svg('check') Запази промените</button></div></div></div>
</section>
@endsection
